// CITATION: GENERATED BY CHATGPT
// I promted ChatGpt with an example of one object in the format I wanted and told it to come up with more.
export interface Student {
  id: number;
  studentName: string;
  A1: number;
  A2: number;
  A3: number;
  A4: number;
}
const fakeGradesData: Student[] = [
  { id: 1, studentName: "Alice Johnson", A1: 92, A2: 88, A3: 91, A4: 87 },
  { id: 2, studentName: "Bob Smith", A1: 85, A2: 82, A3: 80, A4: 90 },
  { id: 3, studentName: "Charlie Brown", A1: 78, A2: 74, A3: 70, A4: 82 },
  { id: 4, studentName: "Diana Prince", A1: 88, A2: 91, A3: 85, A4: 90 },
  { id: 5, studentName: "Edward Norton", A1: 92, A2: 89, A3: 94, A4: 91 },
  { id: 6, studentName: "Fiona Apple", A1: 95, A2: 93, A3: 97, A4: 94 },
  { id: 7, studentName: "George Lucas", A1: 84, A2: 82, A3: 88, A4: 86 },
  { id: 8, studentName: "Hannah Montana", A1: 77, A2: 79, A3: 73, A4: 80 },
  { id: 9, studentName: "Ian McKellen", A1: 89, A2: 87, A3: 90, A4: 88 },
  { id: 10, studentName: "Jessica Alba", A1: 93, A2: 90, A3: 92, A4: 95 }
];

export default fakeGradesData;